image: Visual Studio 2017
before_build:
  - nuget restore "Source\XamarinPrismMyCalculator.sln"
build_script:
  - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release" "Source\XamarinPrismMyCalculator\XamarinPrismMyCalculator.Android\XamarinPrismMyCalculator.Android.csproj"
after_build:
  - ps: Push-AppveyorArtifact Source\XamarinPrismMyCalculator\XamarinPrismMyCalculator.Android\bin\Release\com.amarapp.calculator-Signed.apk -FileName Android\$("Calculator"+".apk")

artifacts:
  - path: Source\XamarinPrismMyCalculator\XamarinPrismMyCalculator.Android\bin\Release\com.amarapp.calculator-Signed.apk
