image: Visual Studio 2017
before_build:
  - nuget restore "Source\XamarinPrismMyCalculator.sln"
  
  - cmd: msbuild "Source\XamarinPrismMyCalculator.Versioning\XamarinPrismMyCalculator.Versioning.csproj" "/p:Configuration=Release"

  "Source\XamarinPrismMyCalculator.Versioning\bin\Release\XamarinPrismMyCalculator.Versioning.exe" "16.1.0.0" "3"
  
build_script:
  
  - msbuild "/t:SignAndroidPackage" "/p:Configuration=Release" "Source\XamarinPrismMyCalculator\XamarinPrismMyCalculator.Android\XamarinPrismMyCalculator.Android.csproj"
  
  - msbuild "Source\XamarinPrismMyCalculator\XamarinPrismMyCalculator.UWP\XamarinPrismMyCalculator.UWP.csproj" /p:Configuration=Release /p:AppxPackageDir="Build\AppxPackages\\" /p:AppxBundlePlatforms="x64" /p:AppxBundle=Always
  
after_build:
  - ps: Push-AppveyorArtifact Source\XamarinPrismMyCalculator\XamarinPrismMyCalculator.Android\bin\Release\com.amarapp.calculator-Signed.apk -FileName Android\$("Calculator"+".apk") -DeploymentName "Android"
  - ps: Push-AppveyorArtifact "Source\XamarinPrismMyCalculator\XamarinPrismMyCalculator.UWP\Build\AppxPackages\**\*.appxbundle" -FileName Windows\$("Calculator"+".appxbundle")
